### ISSUE TITLE
Add temporal flag documentation

### ISSUE THREAD

**Issue by Benjaki2** [nasa-gibs/worldview-options-eosdis#141]
Start date and end date can both be adjusted using the `temporal` flag. If you want to adjust the end date, the `inactive` flag must be set to true

&& note that `startDate` flag is still used for layers that do not have a `startDate` tag in the `getCapabilities` (WMS layers)

**Comment by ZachTRice** [comment]
The `period` flag should have better documentation. Specifically after #149 has been implemented.

When processTemporalLayer.py is ran during the build process, `"daily"` or `"subdaily"` is automatically set based on the `<Value>` ISO 8601 information in the GC document. Daily and subdaily layers have a start and end date variable added to their layer JSON information. 

The `period` flag can also be manually set to `static`  so that no start date is used. These variables effect how a layer is displayed on the timeline. `static` layers will have no start_date and will always show on the timeline. Otherwise, the layer in the timeline will start on the start_date.

In the future, the period flag will also be tied to how often a layer is requested when moving the timeline. Additionally, there will be `"monthly"`, `"yearly"` and _possibly_ `"weekly"` & `"seasonal"` flags. Manually setting the period flag in the layer json to one of these values will lock the layer into only being re-requested within that time frame.
